# Generated by Django 4.0.6 on 2022-07-09 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='irl_photo',
            field=models.CharField(default='...', max_length=400),
        ),
    ]
