# Generated by Django 4.0.6 on 2022-07-09 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_irl_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='title',
            field=models.CharField(default='Food', max_length=200),
        ),
    ]
