# Generated by Django 4.0.6 on 2022-07-09 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='anime',
            field=models.CharField(default='', max_length=200),
        ),
    ]
